---
file: '/mnt/c/Users/stk/Downloads/excel/tmpl/template.xlsx'
sheets:
  'INV':
    src.start: 18
    src.end: 480
    dst.sheet: '表体'
    dst.start: 2
    mapping:
      1: 3
      2: 2
      3: 7
      4: 6
      5: 8
      6: 9
      7: 4
      8: 1
#  'PKL':
#    src.start: 18
#    src.end: 480
#    dst.sheet: '表体'
#    dst.start: 2
#    mapping:
#      1: 3
#      2: 2
#      3: 7
#      4: 6
#      5: 8
#      6: 9
#      7: 4
#      8: 1
#  'CRT':
#    src.start: 14
#    src.end: 476
#    dst.sheet: '表体'
#    dst.start: 2
#    mapping:
#      1: 3
#      2: 2
#      3: 7
#      4: 6
#      5: 8
#      6: 9
