---
file: '/mnt/c/Users/stk/Downloads/excel/tmpl/moban.xlsx'
sheets:
  'INV':
    src_start: 18
    src_end: 480
    dst_sheet: '表体'
    dst_start: 2
    mapping:
      1: 3
      2: 2
      3: 7
      4: 6
      5: 8
      6: 9
      7: 4
      8: 1
#  'PKL':
#    src_start: 18
#    src_end: 480
#    dst_sheet: '表体'
#    dst_start: 2
#    mapping:
#      1: 3
#      2: 2
#      3: 7
#      4: 6
#      5: 8
#      6: 9
#      7: 4
#      8: 1
#  'CRT':
#    src_start: 14
#    src_end: 476
#    dst_sheet: '表体'
#    dst_start: 2
#    mapping:
#      1: 3
#      2: 2
#      3: 7
#      4: 6
#      5: 8
#      6: 9
